version: "3.9"

networks:
  dev:

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Oo332211oo
      POSTGRES_DB: habits_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  backend:
    build:
      context: ./backend
    container_name: backend_app
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:Oo332211oo@db:5432/habits_tracker
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - dev
      
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - dev

volumes:
  postgres_data: