user root;
worker_processes 1;

events {}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;
        server_name localhost;

        # Прокси для бэкенда
        location /api/ {
            proxy_pass http://backend_app:8000; # Прямой проброс без переменных
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Прокси для фронтенда
        location / {
            proxy_pass http://frontend_app:80; # Прямой проброс без переменных и слэша
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}